Sprint 1
Spirals-Team/BtrShop-cloud pull request #1
Opened 2016-11-04 14:29 UTC by Oupsla

2016-11-15 15:56 UTC, duribreux commented on lib/controller.js
> +  findOne(req, res, next) {
Seems to not be used. Should be removed if so.

2016-11-15 16:42 UTC, duribreux requested changes
I should be nice to add a code coverage library also (example: https://www.npmjs.com/package/istanbul)

2016-11-15 16:42 UTC, duribreux commented on model/product/product-controller.js
> +class ProductController extends Controller {
Avoid code duplication, refactor the param check to prevent rewriting it in every method.

2016-11-15 16:42 UTC, duribreux commented on model/product/product-controller.js
> +        res.send(`No product found with this ean`, 400);
Return 404

2016-11-15 16:42 UTC, duribreux commented on model/product/product-router.js
> +  // .put((...args) => controller.update(...args))
Avoid dead code.

2016-11-15 16:42 UTC, duribreux commented on model/user/user-controller.js
> +class UserController extends Controller {}
To be deleted.

2016-11-15 16:42 UTC, duribreux commented on model/user/user-facade.js
> +class UserModel extends Model {}
To be deleted.

2016-11-15 16:42 UTC, duribreux commented on model/user/user-router.js
> +const controller = require('./user-controller');
To be deleted.

2016-11-15 16:42 UTC, duribreux commented on model/user/user-schema.js
> +const userSchema = new Schema({
To be deleted.

2016-11-15 16:42 UTC, duribreux commented on routes.js
> +router.use('/user', user);
Delete this route.

2016-11-15 16:42 UTC, duribreux commented on model/product/product-controller.js
> +        res.send(`No product found with this ean`, 400);
Update swagger based on API modifications.

2016-11-15 16:42 UTC, duribreux commented on test/product-test.js
> +    it('should return an error because product dont exist', (done) => {
This test is strange, it seems you are testing the returned HTTP code both, with 2 different values.
To be confirmed. Check others if needed.

2016-11-15 16:42 UTC, duribreux commented on test/product-test.js
> +    /* it("should return an 404 error",function(done){
Clean if not relevant.

2016-11-15 16:42 UTC, duribreux commented on test/product-test.js
> +
In most of your tests you're writing:
```
.expect(value)
.end((......) => {
   ... should.equal(value)
}
```

After a quick check on supertest, we don't understand why you should check again the returned HTTP code.

2016-11-15 16:42 UTC, duribreux commented on test/route-test.js
> +describe('Routes test', () => {
Same comments about the supposed double check on http response.

2016-11-15 16:42 UTC, duribreux commented on test/route-test.js
> +    .get('/')
This route should exist, it's irrelevant in our API. No welcome message.

2016-11-18 10:13 UTC, Oupsla commented on test/route-test.js
> +    .get('/')
You mean that route should not exist ?
So if a user contact the main page of the API, what I have to send ? An 404 ?

2016-12-02 08:43 UTC, merged