Sprint 2
Spirals-Team/BtrShop-cloud pull request #4
Opened 2017-01-20 09:13 UTC by Oupsla

Intégration d'une liste de beacons grâce à Proximy
Ajout de position aux produits
Calcul d'une trilateration + moyenne de la position

2017-01-21 22:57 UTC, duribreux requested changes

2017-01-21 22:57 UTC, duribreux commented on .eslintignore
> +dist
Also add the dist folder to the .gitignore file and explain steps required to generate it.

2017-01-21 22:57 UTC, duribreux commented on model/beacon/beacon-facade.js
> +      .remove({})
Remove `{}` ?

2017-01-21 22:57 UTC, duribreux commented on model/product/product-facade.js
> +  addPosition(eanQuery, positions) {
Split a bit this methods, that's a lot of things done in it

2017-01-21 22:57 UTC, duribreux commented on util/trilateration.js
> + * @param {Number} dist Distance from [lat, lon] to some point in kilometers
I don't really understand the semantic behind the distance in the beacon.
(x,y) coordinates are easy to figure out but distance... "from some point in km" ? Makes no sense to me. What point ? Is this really the best place to save this value ?

2017-01-21 22:57 UTC, duribreux commented on util/trilateration.js
> +const trilaterate = function(beacons) {
No libs to that ? oO'

2017-01-29 18:30 UTC, Oupsla commented on model/beacon/beacon-facade.js
> +      .remove({})
This method has been created to update the entire list of beacon from the website proximy
So first I have to remove all beacons in db

2017-01-29 18:30 UTC, Oupsla commented on .eslintignore
> +dist
The dist folder is not generated, you only have to change the dist/swagger.yaml
You can use an editor like : http://editor.swagger.io/

2017-01-29 18:35 UTC, Oupsla commented on util/trilateration.js
> + * @param {Number} dist Distance from [lat, lon] to some point in kilometers
Thanks to proximy, we know where all beacons are (with their latitudes and longitudes).
The phone gives us a list of distance between detected beacons and the phone himself

So this method returns the approximative position of the user

2017-01-29 18:36 UTC, Oupsla commented on util/trilateration.js
> +const trilaterate = function(beacons) {
Only one but not trustable

2017-05-25 18:46 UTC, merged